site:
  title: StyleBI Documentation
  url: https://www.inetsoft.com/docs/stylebi
  start_page: InetSoftUserDocumentation:ROOT:index.adoc

content:
   #edit_url: 'https://repo.inetsoft.com/docs/inetsoft/files/master/{path}'
   sources: 
   - url: ..\
     branches: 'main'
     start_path: InetSoftUserDocumentation

ui:
  bundle:
    url: ..\ui\build\ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
  
antora:
  extensions:
  - require: '@antora/lunr-extension'
  #- antora-router-extension
    
asciidoc:
  attributes:
    testdrive: false
    si: true
    
    

  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll